config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	resources :comments ,:controller => 'comments'
  end
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_presence_of :name, :description
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments ,:dependent=>:destroy

	validates_presence_of :name , :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts ,:dependent=>:destroy
  has_many :comments ,:dependent=>:destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  before_action :set_own_comment, :only => [:update, :edit, :destroy]

  def index
    @comments = @post.comments
  end

  def show

  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render :action => :edit
    end
  end

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post)
    else
      render :action => :new
    end
  end

  def destroy
    # 缺少刪除的action
    @comment.destroy
    flash[:notice] = "刪除成功"
    redirect_to post_path(@post)
  end

  private
  def set_own_comment
    @comment = current_user.comments.find(params[:id])
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:name, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => :index
  before_action :set_post , :only => [:show]
  before_action :set_own_post , :only => [:update , :edit, :destroy]
  def index
    @posts = Post.page(params[:page]).per(5)
  end

  def show
    @comments=@post.comments
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "update success"
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def destroy
    flash[:notice] = "destroy success"
    @post.destroy
    redirect_to posts_path
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "create success"
      redirect_to posts_path
    else
      render :action => :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:name, :description, :category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_own_post
    @post = current_user.posts.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<%= form_for@comment,:url=>post_comment_path(@post) do|c|%>

<%= c.label :name,'Name' %>
<%= c.text_field :name %>
<%= c.label :description,'description' %>
<%= c.text_area :description %>
<%= c.submit %>
<%= link_to	"back" ,post_path(@post)%>
<% end %>

app/views/comments/index.html.erb
<h1>comment index</h1>
<% @comments.each do |c| %>
    <%= c.name %>
    <%= c.description %>
    <%= link_to "show", post_comment_path(@post, c) %>
    <%= link_to "edit", edit_post_comment_path(@post, c) %>
    <%= link_to "delete", post_comment_path(@post, c), :method => :delete %>
<% end %>
<%= link_to "new comment", new_post_comment_path(@post) %>
<br>
<%= link_to "back", posts_path %>

app/views/comments/new.html.erb
<%= form_for@comment,:url=>post_comments_path(@post) do|c|%>

<%= c.label :name,'Name' %>
<%= c.text_field :name %>
<%= c.label :description,'description' %>
<%= c.text_area :description %>
<%= c.submit %>
<%= link_to	"back" ,post_path(@post)%>
<% end %>

app/views/comments/show.html.erb
<h1>show</h1>
<%= @comment.name %>
<%= @comment.description %>

<%= link_to	"back" ,post_comments_path(@post)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Midterm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
	  <p class="alert"><%= alert %></p>
    <% if current_user %>
	    <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
	    <%= link_to('修改密碼', edit_registration_path(:user)) %>
	  <% else %>
	    <%= link_to('註冊', new_registration_path(:user)) %> |
	    <%= link_to('登入', new_session_path(:user)) %>
	  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>
<%= p.collection_select(:category_id, Category.all, :id, :name) %>
<%= p.label :name, 'Name' %>
<%= p.text_field :name %>
<%= p.label :description, 'description' %>
<%= p.text_area :description %>
<%= p.submit %>

app/views/posts/edit.html.erb
<%= form_for @post, :url => post_path(@post), :method => :patch do |p| %>
    <%= render :partial => "form", :locals => { :p => p } %>
<% end %>


<%= link_to "back", posts_path %>

app/views/posts/index.html.erb
<h1>SOS POST</h1>
<ul>
	<% @posts.each do |p| %>
	<li>
		<%= link_to p.name ,post_path(p)%>
		<%= p.created_at %>
		<% if current_user == p.user %>
		<%= link_to 'edit',edit_post_path(p,:id=>p.id) %>
		<%= link_to 'delete',post_path(p,:id=>p.id),:method=>:delete %>
		<% end %>
	</li>
	<% end %>
</ul>

<%= link_to'new post',new_post_path %>
<%= paginate @posts %>

app/views/posts/new.html.erb
<%= form_for @post, :url => posts_path do |p| %>
    <%= render :partial => "form", :locals => { :p => p } %>
<% end %>

<%= link_to "back", posts_path %>

app/views/posts/show.html.erb
<h1>Post show</h1>
<ul>
  <h3>Title</h3>
  <li><%= @post.name %></li>
  <h3>Category</h3>
  <li><%= Category.find(@post.category_id).name %></li>
  <h3>Description</h3>
  <li><%= @post.description %></li>
</ul>

<h1>comment</h1>
<ul>
  <% @comments.each do |c| %>
      <li>
        <h4><%= c.name %></h4>
        <%= c.description %>
        <% if current_user == c.user %>
            <%= link_to "edit", edit_post_comment_path(@post, c) %>
            <%= link_to "delete", post_comment_path(@post, c), :method => :delete %>
        <% end %>
      </li>
  <% end %>
</ul>
<%= link_to "new comment", new_post_comment_path(@post) %>
<%= link_to "back", posts_path %>